// AUTO-GENERATED by scripts/seo/generate-marketing-dates.mjs — DO NOT hand-edit.
// Regenerate after any change to a marketing/legal page's own route file:
//   node scripts/seo/generate-marketing-dates.mjs > src/lib/seo/marketing-dates.ts
//
// Real per-page lastModified derived from each page's own route file's git
// history, not a hand-maintained guess. Replaces the previous hardcoded
// MARKETING_DATES map in sitemap-dates.ts, which went stale by a full month
// on the homepage (see the script's own header comment for the evidence).
// Scope: tracks the page's own route file only, not shared imports — see
// the generator script if that limitation ever needs widening.

export const MARKETING_DATES: Record<string, string> = {
  "/": "2026-09-01",
  "/pricing": "2026-08-20",
  "/faq": "2026-08-20",
  "/why-blackout": "2026-08-20",
  "/methodology": "2026-08-27",
  "/vs/others": "2026-09-01",
  "/tools/gamma-snapshot": "2026-08-23",
  "/about": "2026-09-01",
  "/contact": "2026-08-20",
  "/learn": "2026-08-21",
};
