/**
 * Tool-agent shared runtime — status, findings, RTH loop, CTO reports.
 */
import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { isTradingDayEt, todayEtYmd, etParts } from "../../gha-et-window.mjs";
import { createAuditClient, resolveAuditDbUrl } from "../../pg-audit.mjs";

export function toolAgentDir(toolKey) {
  const root = join(process.cwd(), "audit-output", "tool-agents", toolKey);
  mkdirSync(root, { recursive: true });
  return root;
}

export function inCashRth(now = new Date()) {
  const { weekday, mins } = etParts(now);
  if (weekday === "Sat" || weekday === "Sun") return false;
  return mins >= 9 * 60 + 30 && mins <= 16 * 60;
}

export function appendFinding(toolKey, finding) {
  const path = join(toolAgentDir(toolKey), "findings.ndjson");
  appendFileSync(path, JSON.stringify({ ts: new Date().toISOString(), ...finding }) + "\n");
}

export function writeStatus(toolKey, status) {
  writeFileSync(
    join(toolAgentDir(toolKey), "status.json"),
    JSON.stringify({ ts: new Date().toISOString(), ...status }, null, 2)
  );
}

export function writeCtoReport(toolKey, sections) {
  const ymd = todayEtYmd();
  const lines = [
    `# ${sections.title} — CTO report`,
    ``,
    `**Session:** ${ymd} · **Updated:** ${new Date().toISOString()}`,
    ``,
    ...sections.blocks.flatMap((b) => [`## ${b.heading}`, "", b.body, ""]),
    ``,
    `---`,
    `*Auto-generated by tool-agent \`${toolKey}\`. Fix → PR → merge → re-run \`npm run validate:tool-agent:${toolKey}\`.*`,
  ];
  writeFileSync(join(toolAgentDir(toolKey), `cto-report-${ymd}.md`), lines.join("\n"));
}

export async function cronFetch(base, path, cron) {
  const t0 = performance.now();
  const res = await fetch(`${base}${path}`, {
    headers: { Authorization: `Bearer ${cron}`, Accept: "application/json" },
    signal: AbortSignal.timeout(120_000),
  });
  const text = await res.text();
  let json = null;
  try {
    json = JSON.parse(text);
  } catch {
    json = null;
  }
  return { status: res.status, ms: Math.round(performance.now() - t0), json, raw: text.slice(0, 500) };
}

export function runScript(cmd, args = []) {
  const t0 = Date.now();
  const r = spawnSync(cmd, args, { encoding: "utf8", env: process.env, stdio: "pipe" });
  return {
    ok: r.status === 0,
    exit: r.status,
    ms: Date.now() - t0,
    tail: (r.stdout || r.stderr || "").trim().split("\n").slice(-4).join(" | "),
  };
}

export async function queryPlayOutcomes(surface) {
  const dbUrl = resolveAuditDbUrl();
  if (!dbUrl) return { skip: true, reason: "no DATABASE_URL" };
  const c = createAuditClient(dbUrl);
  await c.connect();
  const ymd = todayEtYmd();
  try {
    if (surface === "spx") {
      const rows = (
        await c.query(
          `SELECT open_play_id, direction, entry_path, grade, score, confidence, outcome,
                  entry_price, exit_price, pnl_pts, closed_at, confirmations, factors
           FROM spx_play_outcomes
           WHERE session_date = $1
           ORDER BY closed_at DESC NULLS FIRST
           LIMIT 40`,
          [ymd]
        )
      ).rows;
      const open = rows.filter((r) => r.outcome === "open");
      const failed = rows.filter((r) => ["stop", "ambiguous"].includes(r.outcome));
      return { surface, session: ymd, open, failed, all: rows };
    }
    if (surface === "nighthawk") {
      const rows = (
        await c.query(
          `SELECT id, ticker, direction, outcome, entry_range_low, entry_range_high,
                  target, stop, score, edition_for, updated_at
           FROM nighthawk_play_outcomes
           WHERE edition_for >= $1::date - INTERVAL '2 days'
           ORDER BY edition_for DESC, resolved_at DESC NULLS FIRST
           LIMIT 30`,
          [ymd]
        )
      ).rows;
      const failed = rows.filter((r) => ["stop", "ambiguous"].includes(r.outcome));
      return { surface, session: ymd, failed, all: rows };
    }
    if (surface === "zerodte") {
      const rows = (
        await c.query(
          `SELECT id, ticker, setup_type, flagged_at, premium_usd, meta
           FROM zerodte_setup_log
           WHERE flagged_at::date = $1::date
           ORDER BY flagged_at DESC
           LIMIT 40`,
          [ymd]
        )
      ).rows;
      return { surface, session: ymd, setups: rows };
    }
    return { surface, skip: true };
  } finally {
    await c.end();
  }
}

export function analyzeSpxPlay(playJson, outcomes) {
  const analysis = [];
  if (!playJson) return analysis;
  const action = playJson.action;
  const grade = playJson.grade ?? playJson.signal_grade;
  if (action === "SCANNING" && playJson.confirmations?.checks?.length) {
    analysis.push({
      severity: "P1",
      id: "play-scanning-stale-confirmations",
      detail: "SCANNING carries stale confirmation checks",
    });
  }
  if (action && !["SCANNING", "WATCH", "ENTER", "HOLD"].includes(action)) {
    analysis.push({ severity: "P2", id: "play-unknown-action", detail: `action=${action}` });
  }
  for (const f of outcomes?.failed ?? []) {
    analysis.push({
      severity: "P1",
      id: `play-failed-${f.open_play_id ?? f.id}`,
      detail: `${f.direction} ${f.entry_path} → ${f.outcome} pnl_pts=${f.pnl_pts ?? "?"} grade=${f.grade}`,
    });
  }
  if (grade && Number(playJson.score) < 40 && action === "ENTER") {
    analysis.push({
      severity: "P1",
      id: "play-low-score-enter",
      detail: `ENTER with score ${playJson.score} grade ${grade}`,
    });
  }
  return analysis;
}

export async function runAgentLoop(agent, opts = {}) {
  const { once = false, force = false, waitOpen = false } = opts;
  const ymd = todayEtYmd();

  if (waitOpen) {
    const { mins } = etParts();
    const open = 9 * 60 + 30;
    if (isTradingDayEt(ymd) && mins < open) {
      const waitMs = (open - mins) * 60_000;
      console.log(`[${agent.key}] waiting ${Math.round(waitMs / 1000)}s until 09:30 ET`);
      await new Promise((r) => setTimeout(r, waitMs));
    }
  }

  if (!force && !isTradingDayEt(ymd)) {
    console.log(`[${agent.key}] not a trading day`);
    return 0;
  }

  let tick = 0;
  const started = Date.now();
  const endAt = once ? started + 90_000 : started + 6.5 * 60 * 60 * 1000;

  console.log(`\n=== Tool agent: ${agent.label} (${agent.key}) ===\n`);

  while (Date.now() < endAt) {
    if (!force && !once && !inCashRth()) break;
    tick += 1;
    const result = await agent.tick(tick);
    writeStatus(agent.key, {
      tick,
      label: agent.label,
      uptime_ms: Date.now() - started,
      ...result,
    });
    if (tick % agent.reportEvery === 0) {
      agent.writeReport?.(result);
    }
    if (once && tick >= 2) break;
    await new Promise((r) => setTimeout(r, agent.intervalMs));
  }

  const p1 = (agent.lastFindings ?? []).filter((f) => f.severity === "P1");
  console.log(`\n[${agent.key}] done ticks=${tick} P1=${p1.length}\n`);
  return p1.length ? 1 : 0;
}
