import type { TerminalPlay } from "@/features/nighthawk/command-deck/types";

const SESSION = "2026-09-01";

function legacyPlay(partial: TerminalPlay): TerminalPlay {
  return partial;
}

/** Rich fixture for local Legacy board UI preview — dev only (no adapters / DB imports). */
export const LEGACY_BOARD_DEV_PLAYS: TerminalPlay[] = [
  legacyPlay({
    id: "LEGACY:NVDA",
    ticker: "NVDA",
    direction: "LONG",
    contract: "$185 CALL @ $4.50 — Jan 17",
    occ: "NVDA260117C00185000",
    rank: 1,
    score: 84,
    status: "OPEN",
    horizon: "LEGACY",
    exitModel: "PLAN",
    factors: [
      { label: "Flow", points: 18 },
      { label: "Technicals", points: 12 },
    ],
    gates: [],
    regime: "pre-market CONFIRMED",
    thesisBreak: { level: "intact" },
    tierLabel: "A",
    recommendation: "BUY",
    recNote: "Pre-market confirmed — thesis intact, entry levels hold.",
    thesis: "Flow-led breakout continuation — gamma squeeze setup into earnings drift.",
    keySignal: "3-day call sweep streak above VWAP",
    entryRange: "$178.50 – $180.20",
    targetLevel: "$192",
    stopLevel: "$172",
    entryCostPerContract: 4.5,
    mark: 6.8,
    pnlPct: 51,
    peak: 58,
    stockMovePct: 3.2,
    progress: 0.62,
    morningStatus: "CONFIRMED",
    markAsOf: `${SESSION}T19:42:00.000Z`,
  }),
  legacyPlay({
    id: "LEGACY:INTC",
    ticker: "INTC",
    direction: "LONG",
    contract: "$32 CALL @ $1.20 — Jan 17",
    occ: "INTC260117C00032000",
    rank: 2,
    score: 76,
    status: "OPEN",
    horizon: "LEGACY",
    exitModel: "PLAN",
    factors: [
      { label: "Technicals", points: 14 },
      { label: "Flow", points: 10 },
    ],
    gates: [],
    regime: "pre-market CONFIRMED",
    thesisBreak: { level: "intact" },
    tierLabel: "A",
    recommendation: "BUY",
    recNote: "Pre-market confirmed — thesis intact.",
    thesis: "Semiconductor rotation catch-up — desk likes the risk/reward into reclaim.",
    entryCostPerContract: 1.2,
    mark: 2.1,
    pnlPct: 75,
    peak: 82,
    stockMovePct: 4.8,
    progress: 0.88,
    morningStatus: "CONFIRMED",
    markAsOf: `${SESSION}T19:38:00.000Z`,
  }),
  legacyPlay({
    id: "LEGACY:AMD",
    ticker: "AMD",
    direction: "LONG",
    contract: "$165 CALL @ $3.10 — Jan 17",
    occ: "AMD260117C00165000",
    rank: 3,
    score: 71,
    status: "WATCH",
    horizon: "LEGACY",
    exitModel: "PLAN",
    factors: [
      { label: "Technicals", points: 11 },
      { label: "Flow", points: 8 },
    ],
    gates: [{ label: "Gap below entry band", ok: false }],
    regime: "pre-market DEGRADED",
    thesisBreak: { level: "warn", note: "Gap below entry band at open" },
    tierLabel: "B",
    recommendation: "HOLD",
    recNote: "DEGRADED — conditions shifted; validate before entry",
    thesis: "Pullback entry into prior breakout shelf — needs follow-through.",
    entryCostPerContract: 3.1,
    mark: 2.4,
    pnlPct: -23,
    peak: 12,
    stockMovePct: -1.4,
    progress: 0.18,
    morningStatus: "DEGRADED",
    markAsOf: `${SESSION}T19:35:00.000Z`,
  }),
  legacyPlay({
    id: "LEGACY:TSLA",
    ticker: "TSLA",
    direction: "SHORT",
    contract: "$240 PUT @ $5.80 — Jan 17",
    occ: "TSLA260117P00240000",
    rank: 4,
    score: 68,
    status: "SKIP",
    horizon: "LEGACY",
    exitModel: "PLAN",
    factors: [
      { label: "Flow", points: 9 },
      { label: "Positioning", points: 7 },
    ],
    gates: [],
    regime: "INVALIDATED — pulled",
    thesisBreak: { level: "break", note: "Opened above stop — setup broken" },
    tierLabel: "B",
    recommendation: "SELL",
    recNote: "PULLED — Invalidated at pre-market screening",
    thesis: "Failed reclaim into distribution — short gamma fade candidate.",
    entryCostPerContract: 5.8,
    mark: 3.2,
    pnlPct: -45,
    peak: 8,
    stockMovePct: 2.1,
    morningStatus: "INVALIDATED",
    pulled: true,
    markAsOf: `${SESSION}T09:05:00.000Z`,
  }),
  legacyPlay({
    id: "LEGACY:AAPL",
    ticker: "AAPL",
    direction: "LONG",
    contract: "$230 CALL @ $2.85 — Jan 17",
    occ: "AAPL260117C00230000",
    rank: 5,
    score: 65,
    status: "WATCH",
    horizon: "LEGACY",
    exitModel: "PLAN",
    factors: [
      { label: "Technicals", points: 9 },
      { label: "Flow", points: 6 },
    ],
    gates: [],
    regime: "pre-market unverified",
    thesisBreak: { level: "unknown", note: "morning confirm has not run yet" },
    tierLabel: "B",
    recommendation: "HOLD",
    recNote: "Evening edition — pre-market confirm posts before the open.",
    thesis: "Range compression into catalyst week — defined-risk call spread proxy.",
    entryCostPerContract: 2.85,
    mark: 2.9,
    pnlPct: 2,
    peak: 9,
    stockMovePct: 0.4,
    progress: 0.12,
    morningStatus: "UNVERIFIED",
    markAsOf: `${SESSION}T19:30:00.000Z`,
  }),
];

export const LEGACY_BOARD_DEV_SESSION = SESSION;
