import type { VectorPickBoardResponse } from "@/features/nighthawk/components/VectorPickLogBoard.types";

const SESSION = "2026-09-01";

function contract(ticker: string, strike: number, side: "call" | "put", label: string) {
  const occ = `${ticker}260117${side === "call" ? "C" : "P"}${String(strike * 1000).padStart(8, "0")}`;
  return {
    occ,
    side,
    strike,
    expiry: "2026-01-17",
    label,
  };
}

/** Rich fixture for local Vector board UI preview — dev only. */
export const VECTOR_BOARD_DEV_FIXTURE: VectorPickBoardResponse = {
  available: true,
  session_date: SESSION,
  note: "DEV FIXTURE — premium % is option mid vs pick entry (not 0DTE managed P&L).",
  coverage: {
    leaders: 8,
    winners: 3,
    closed: 5,
    note: "Preview data for UI review before merge.",
  },
  winners: [
    {
      id: 101,
      ticker: "INTC",
      session_date: SESSION,
      contract: contract("INTC", 30, "call", "30C Jan'26"),
      rank: 1,
      role: "leader",
      entry_mid: 1.2,
      live_mid: 2.1,
      premium_pct_from_entry: 75,
      peak_premium_pct: 82,
      action_status: "still_buy",
      action_reason: "Universe sweep winner — flow still constructive",
      setup_invalidated: false,
      spot: 31.4,
      updated_at: `${SESSION}T19:42:00.000Z`,
      is_winner: true,
      tier: "elite",
    },
    {
      id: 102,
      ticker: "NVDA",
      session_date: SESSION,
      contract: contract("NVDA", 180, "call", "180C Jan'26"),
      rank: 2,
      role: "leader",
      entry_mid: 4.5,
      live_mid: 7.2,
      premium_pct_from_entry: 60,
      peak_premium_pct: 68,
      action_status: "still_buy",
      action_reason: "Hit +50% floor intraday — holding runner",
      setup_invalidated: false,
      spot: 182,
      updated_at: `${SESSION}T19:38:00.000Z`,
      is_winner: true,
      tier: "elite",
    },
    {
      id: 103,
      ticker: "AMD",
      session_date: SESSION,
      contract: contract("AMD", 160, "call", "160C Jan'26"),
      rank: 3,
      role: "leader",
      entry_mid: 3.1,
      live_mid: 4.8,
      premium_pct_from_entry: 55,
      peak_premium_pct: 61,
      action_status: "caution",
      action_reason: "Winner floor met — desk flagged caution into close",
      setup_invalidated: false,
      spot: 161,
      updated_at: `${SESSION}T19:35:00.000Z`,
      is_winner: true,
      tier: "standard",
    },
  ],
  leaders: [
    {
      id: 201,
      ticker: "INTC",
      session_date: SESSION,
      contract: contract("INTC", 30, "call", "30C Jan'26"),
      rank: 1,
      role: "leader",
      entry_mid: 1.2,
      live_mid: 2.1,
      premium_pct_from_entry: 75,
      peak_premium_pct: 82,
      action_status: "still_buy",
      action_reason: "Universe sweep winner",
      setup_invalidated: false,
      spot: 31.4,
      updated_at: `${SESSION}T19:42:00.000Z`,
      is_winner: true,
      tier: "elite",
    },
    {
      id: 202,
      ticker: "NVDA",
      session_date: SESSION,
      contract: contract("NVDA", 180, "call", "180C Jan'26"),
      rank: 2,
      role: "leader",
      entry_mid: 4.5,
      live_mid: 7.2,
      premium_pct_from_entry: 60,
      peak_premium_pct: 68,
      action_status: "still_buy",
      action_reason: "Hit +50% floor",
      setup_invalidated: false,
      spot: 182,
      updated_at: `${SESSION}T19:38:00.000Z`,
      is_winner: true,
      tier: "elite",
    },
    {
      id: 203,
      ticker: "AMD",
      session_date: SESSION,
      contract: contract("AMD", 160, "call", "160C Jan'26"),
      rank: 3,
      role: "leader",
      entry_mid: 3.1,
      live_mid: 4.8,
      premium_pct_from_entry: 55,
      peak_premium_pct: 61,
      action_status: "caution",
      action_reason: "Winner floor met — caution",
      setup_invalidated: false,
      spot: 161,
      updated_at: `${SESSION}T19:35:00.000Z`,
      is_winner: true,
      tier: "standard",
    },
    {
      id: 204,
      ticker: "TSLA",
      session_date: SESSION,
      contract: contract("TSLA", 250, "call", "250C Jan'26"),
      rank: 4,
      role: "runner",
      entry_mid: 2.8,
      live_mid: 3.6,
      premium_pct_from_entry: 28,
      peak_premium_pct: 35,
      action_status: "still_buy",
      action_reason: "+15% runner — building toward winner floor",
      setup_invalidated: false,
      spot: 252,
      updated_at: `${SESSION}T19:30:00.000Z`,
      is_winner: false,
      tier: "elite",
    },
    {
      id: 205,
      ticker: "META",
      session_date: SESSION,
      contract: contract("META", 520, "call", "520C Jan'26"),
      rank: 5,
      role: "runner",
      entry_mid: 6.2,
      live_mid: 7.5,
      premium_pct_from_entry: 21,
      peak_premium_pct: 24,
      action_status: "still_buy",
      action_reason: "Mid-band runner — holding above +15%",
      setup_invalidated: false,
      spot: 522,
      updated_at: `${SESSION}T19:28:00.000Z`,
      is_winner: false,
      tier: "standard",
    },
    {
      id: 206,
      ticker: "AAPL",
      session_date: SESSION,
      contract: contract("AAPL", 220, "call", "220C Jan'26"),
      rank: 6,
      role: "live",
      entry_mid: 1.9,
      live_mid: 2.0,
      premium_pct_from_entry: 5,
      peak_premium_pct: 12,
      action_status: "still_buy",
      action_reason: "Live leader — sub-runner, thesis intact",
      setup_invalidated: false,
      spot: 221,
      updated_at: `${SESSION}T19:25:00.000Z`,
      is_winner: false,
      tier: "standard",
    },
    {
      id: 207,
      ticker: "MSFT",
      session_date: SESSION,
      contract: contract("MSFT", 420, "call", "420C Jan'26"),
      rank: 7,
      role: "live",
      entry_mid: 3.4,
      live_mid: 2.9,
      premium_pct_from_entry: -15,
      peak_premium_pct: 8,
      action_status: "caution",
      action_reason: "Gave back peak — caution flag",
      setup_invalidated: false,
      spot: 418,
      updated_at: `${SESSION}T19:20:00.000Z`,
      is_winner: false,
      tier: "elite",
    },
    {
      id: 208,
      ticker: "PLTR",
      session_date: SESSION,
      contract: contract("PLTR", 28, "call", "28C Jan'26"),
      rank: 8,
      role: "live",
      entry_mid: 0.85,
      live_mid: 0.72,
      premium_pct_from_entry: -15,
      peak_premium_pct: 5,
      action_status: "still_buy",
      action_reason: "Soft tape — still on board",
      setup_invalidated: true,
      spot: 27.5,
      updated_at: `${SESSION}T19:15:00.000Z`,
      is_winner: false,
      tier: "standard",
    },
  ],
  closed: [
    {
      id: 301,
      ticker: "KSS",
      session_date: SESSION,
      contract: contract("KSS", 18.5, "put", "18.5P Sep'26"),
      rank: 1,
      role: null,
      entry_mid: 0.45,
      close_mid: 1.0,
      premium_pct_from_entry: 122,
      close_reason: "Premium extended +122% since pick — chase risk",
      setup_invalidated: false,
      spot: 17.8,
      closed_at: `${SESSION}T16:39:00.000Z`,
    },
    {
      id: 302,
      ticker: "GME",
      session_date: "2026-08-29",
      contract: contract("GME", 25, "call", "25C Jan'26"),
      rank: 2,
      role: null,
      entry_mid: 1.1,
      close_mid: 0.55,
      premium_pct_from_entry: -50,
      close_reason: "Setup invalidated — flow reversed",
      setup_invalidated: true,
      spot: 23.5,
      closed_at: "2026-08-29T15:10:00.000Z",
    },
    {
      id: 303,
      ticker: "SOFI",
      session_date: "2026-08-28",
      contract: contract("SOFI", 14, "call", "14C Jan'26"),
      rank: 3,
      role: null,
      entry_mid: 0.6,
      close_mid: 0.9,
      premium_pct_from_entry: 50,
      close_reason: "Desk cap — trimmed at floor",
      setup_invalidated: false,
      spot: 14.5,
      closed_at: "2026-08-28T18:00:00.000Z",
    },
    {
      id: 304,
      ticker: "COIN",
      session_date: "2026-08-27",
      contract: contract("COIN", 280, "put", "280P Jan'26"),
      rank: 4,
      role: null,
      entry_mid: 5.2,
      close_mid: 4.1,
      premium_pct_from_entry: -21,
      close_reason: "Premium chase — extended entry",
      setup_invalidated: false,
      spot: 285,
      closed_at: "2026-08-27T17:45:00.000Z",
    },
    {
      id: 305,
      ticker: "SMCI",
      session_date: "2026-08-26",
      contract: contract("SMCI", 45, "call", "45C Jan'26"),
      rank: 5,
      role: null,
      entry_mid: 2.0,
      close_mid: 2.8,
      premium_pct_from_entry: 40,
      close_reason: "Closed at trim — runner didn't reach floor",
      setup_invalidated: false,
      spot: 46,
      closed_at: "2026-08-26T16:20:00.000Z",
    },
  ],
};
