/**
 * Dev fixture for the 0DTE Command Deck — exercises session stats, gate blocks, Vector cross-links.
 * Used by /zerodte-command-preview (dev-only, no Clerk/DB).
 */
import type { BoardResp } from "@/features/nighthawk/command-deck/zerodte-sources";

export const ZERODTE_COMMAND_DEV_FIXTURE: BoardResp = {
  available: true,
  upstream_ok: true,
  as_of: new Date().toISOString(),
  session: {
    date: "2026-09-03",
    trading_day: true,
    heat: { state: "ACTIVE", note: "Dev fixture — RTH active" },
  },
  session_stats: {
    scanned: 4,
    commit_ready: 1,
    gate_blocked: 2,
    committed_open: 1,
    committed_closed: 1,
    top_block_code: "cortex_gex_walls",
    top_block_label: "Cortex · gex walls",
  },
  vector_pulse_by_ticker: {
    NVDA: {
      premium_pct: 62,
      peak_premium_pct: 78,
      action_status: "caution",
      is_winner: true,
      is_runner: false,
    },
    TSLA: {
      premium_pct: 22,
      peak_premium_pct: 28,
      action_status: "still_buy",
      is_winner: false,
      is_runner: true,
    },
  },
  market_state: {
    regime_label: "trend",
    regime_structure: "trend",
    confidence: 0.72,
    summary: "Fixture regime — FLOW weight elevated",
    rail_weights: { FLOW: 1.2, BREAKOUT: 1.0, PIN: 0.9 },
    calibration_shadow: null,
  },
  discovery_funnel: {
    detected_tickers: 47,
    gate_blocked_events: 128,
    commit_events: 2,
    top_gate: "cortex_gex_walls",
    top_gate_label: "Cortex · gex walls",
    top_gate_n: 34,
    summary: "Top gate today: Cortex · gex walls (34)",
  },
  setups: [
    {
      ticker: "NVDA",
      direction: "long",
      score: 78,
      top_strike: 128,
      dte: 0,
      discovery_origin: ["FLOW", "BREAKOUT"],
      gate: { verdict: "COMMIT", blocks: [] },
      plan: { occ: "NVDA250903C00128000", mark: 2.45, bid: 2.4, ask: 2.5, stop_premium: 1.22, target_premium: 4.9 },
      confluence: { confirmations: 2 },
      first_seen: new Date(Date.now() - 12 * 60_000).toISOString(),
    },
    {
      ticker: "META",
      direction: "long",
      score: 71,
      top_strike: 585,
      dte: 0,
      discovery_origin: ["FLOW"],
      gate: {
        verdict: "BLOCKED",
        blocks: [
          {
            code: "cortex_gex_walls",
            reason: "Cortex gex-walls oppose — dealer wall in path on the long side.",
          },
        ],
      },
      plan: { occ: "META250903C00585000", mark: 1.85, bid: 1.8, ask: 1.92 },
      first_seen: new Date(Date.now() - 8 * 60_000).toISOString(),
    },
    {
      ticker: "TSLA",
      direction: "short",
      score: 69,
      top_strike: 245,
      dte: 0,
      discovery_origin: ["BREAKOUT"],
      gate: {
        verdict: "BLOCKED",
        blocks: [
          { code: "score_floor", reason: "Score 69 is below the 75 prime floor for single-rail BREAKOUT." },
        ],
      },
      plan: { occ: "TSLA250903P00245000", mark: 3.1, bid: 3.05, ask: 3.18 },
      first_seen: new Date(Date.now() - 5 * 60_000).toISOString(),
    },
    {
      ticker: "AMD",
      direction: "long",
      score: 66,
      top_strike: 162,
      dte: 0,
      discovery_origin: ["FLOW"],
      gate: { verdict: "COMMIT", blocks: [] },
      plan: { occ: "AMD250903C00162000", mark: 1.2, bid: 1.15, ask: 1.25 },
      first_seen: new Date(Date.now() - 3 * 60_000).toISOString(),
    },
  ],
  ledger: [
    {
      ticker: "MARA",
      direction: "long",
      status: "OPEN",
      score: 74,
      top_strike: 18,
      entry_premium: 0.62,
      last_mark: 0.71,
      live_pnl_pct: 14.5,
      occ: "MARA250903C00018000",
      first_flagged_at: new Date(Date.now() - 45 * 60_000).toISOString(),
      discovery_origin: ["FLOW"],
      tier: { tier: "B" },
    },
    {
      ticker: "CRCL",
      direction: "long",
      status: "CLOSED",
      score: 70,
      top_strike: 42,
      entry_premium: 1.1,
      last_mark: 1.05,
      live_pnl_pct: -4.5,
      exit_pnl_pct: -4.5,
      closed_reason: "time_stop",
      occ: "CRCL250903C00042000",
      first_flagged_at: new Date(Date.now() - 3 * 60 * 60_000).toISOString(),
      discovery_origin: ["FLOW"],
      tier: { tier: "C" },
    },
  ],
  allocation: [],
  covered_elsewhere: [],
};
