import { createHmac, timingSafeEqual } from "node:crypto";
import { SITE } from "@/lib/site";

/**
 * Signs/verifies one-click unsubscribe links (RFC 8058) without a dedicated
 * secret — reuses RESEND_API_KEY as HMAC key material, since it's already a
 * server-only secret and adding a new env var would mean another deploy
 * coordination step for zero added security (the token only needs to prove
 * "this link was generated by us for this email," not stand alone as a
 * credential). Truncated to 128 bits (32 hex chars) — plenty for an
 * unsubscribe link, no need for the full digest.
 */
function hmacKey(): string | null {
  return process.env.RESEND_API_KEY?.trim() || null;
}

export function signUnsubscribeToken(email: string): string | null {
  const key = hmacKey();
  if (!key) return null;
  return createHmac("sha256", key).update(email.trim().toLowerCase()).digest("hex").slice(0, 32);
}

export function verifyUnsubscribeToken(email: string, token: string): boolean {
  const expected = signUnsubscribeToken(email);
  if (!expected || !token) return false;
  const a = Buffer.from(expected);
  const b = Buffer.from(token);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/** Absolute unsubscribe URL for a given recipient — used both for the visible
 *  footer link and the List-Unsubscribe header on marketing-category sends. */
export function unsubscribeUrl(email: string): string | null {
  const token = signUnsubscribeToken(email);
  if (!token) return null;
  return `${SITE.url}/api/public/email-unsubscribe?email=${encodeURIComponent(email.trim().toLowerCase())}&token=${token}`;
}

/**
 * One-stop shop for a marketing-category send: the footer link (pass to
 * emailLayout's unsubscribeUrl) plus the RFC 8058 headers (pass to
 * sendEmail's headers) — both derived from the same signed link so they
 * always point at the same place. Returns nulls/empty when RESEND_API_KEY
 * isn't set (no key material to sign with) rather than throwing — a send
 * without a working unsubscribe link is still better than no send at all,
 * same fail-open posture as the rest of the email system.
 */
export function marketingUnsubscribe(email: string): { url: string | null; headers: Record<string, string> } {
  const url = unsubscribeUrl(email);
  if (!url) return { url: null, headers: {} };
  return {
    url,
    headers: {
      "List-Unsubscribe": `<mailto:support@blackouttrades.com?subject=unsubscribe>, <${url}>`,
      "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
    },
  };
}
