// AUTO-GENERATED by scripts/seo/generate-article-dates.mjs — DO NOT hand-edit.
// Regenerate after any change to src/lib/learn/articles.ts:
//   node scripts/seo/generate-article-dates.mjs > src/lib/learn/article-dates.ts
//
// Real per-article datePublished (first git commit introducing the article) and
// dateModified (most recent git-blame date across the article's full block) —
// derived from actual git history, not fabricated. See docs/audit/FINDINGS.md
// (2026-08-08, uniform article dates finding) for why this replaced the single
// shared ARTICLE_DATE_PUBLISHED/ARTICLE_DATE_MODIFIED constant.

export type ArticleDateEntry = { datePublished: string; dateModified: string };

export const ARTICLE_DATES: Record<string, ArticleDateEntry> = {
  "dealer-gamma-options-flow-guide": { datePublished: "2026-07-31", dateModified: "2026-08-03" },
  "what-is-dealer-gamma-exposure": { datePublished: "2026-07-31", dateModified: "2026-08-03" },
  "gamma-flip-explained": { datePublished: "2026-07-31", dateModified: "2026-08-02" },
  "call-wall-put-wall-explained": { datePublished: "2026-07-31", dateModified: "2026-08-02" },
  "what-is-gex": { datePublished: "2026-07-31", dateModified: "2026-08-03" },
  "0dte-spx-options-strategy": { datePublished: "2026-07-31", dateModified: "2026-08-03" },
  "is-0dte-gambling": { datePublished: "2026-07-31", dateModified: "2026-08-03" },
  "how-to-read-options-flow": { datePublished: "2026-07-31", dateModified: "2026-08-02" },
  "gamma-squeeze-explained": { datePublished: "2026-07-31", dateModified: "2026-08-02" },
  "options-trading-glossary": { datePublished: "2026-07-31", dateModified: "2026-08-08" },
  "iron-condor-strategy-guide": { datePublished: "2026-08-02", dateModified: "2026-08-08" },
  "what-is-dark-pool-trading": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "options-greeks-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "implied-volatility-explained": { datePublished: "2026-08-02", dateModified: "2026-08-08" },
  "unusual-options-activity-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "max-pain-options-explained": { datePublished: "2026-08-02", dateModified: "2026-08-08" },
  "delta-hedging-explained": { datePublished: "2026-08-02", dateModified: "2026-08-03" },
  "spx-slayer-dashboard-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "spx-slayer-play-grades-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "spx-slayer-gex-matrix-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "spx-slayer-lotto-power-hour": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "thermal-heatmap-reading-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "thermal-four-lenses-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "thermal-strike-selection-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "helix-flow-scanner-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "helix-flow-signals-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "helix-dark-pool-analysis": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "night-hawk-evening-edition-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "night-hawk-0dte-command-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "night-hawk-cortex-evidence-system": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "largo-ai-terminal-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "largo-ai-market-analysis-tips": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "vector-scanner-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "vwap-trading-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "options-expiration-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "how-to-read-options-chain": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "theta-decay-options-explained": { datePublished: "2026-08-02", dateModified: "2026-08-08" },
  "open-interest-options-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "vix-trading-guide": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "credit-spreads-strategy-guide": { datePublished: "2026-08-02", dateModified: "2026-08-08" },
  "pin-risk-options-explained": { datePublished: "2026-08-02", dateModified: "2026-08-02" },
  "options-volume-analysis": { datePublished: "2026-08-02", dateModified: "2026-08-03" },
  "how-to-trade-spx-options": { datePublished: "2026-08-03", dateModified: "2026-08-08" },
  "market-maker-hedging-explained": { datePublished: "2026-08-03", dateModified: "2026-08-03" },
  "best-0dte-trading-strategies": { datePublished: "2026-08-03", dateModified: "2026-08-08" },
  "spx-vs-spy-options-explained": { datePublished: "2026-08-08", dateModified: "2026-08-08" },
  "options-tax-treatment-1256": { datePublished: "2026-08-08", dateModified: "2026-08-08" },
  "wheel-strategy-cash-secured-puts": { datePublished: "2026-08-08", dateModified: "2026-08-08" },
  "straddles-strangles-options-explained": { datePublished: "2026-08-08", dateModified: "2026-08-08" },
  "options-assignment-exercise-explained": { datePublished: "2026-08-08", dateModified: "2026-08-08" },
  "butterfly-spread-strategy-guide": { datePublished: "2026-08-08", dateModified: "2026-08-08" },
};
